site_name: Trucos y recordatorios de IT
site_description: Proyecto personal con trucos y recordatorios de IT
site_author: Tecnicaso
site_url: https://techdocs.ivangarciaalcaide.es

theme:
  name: material
  custom_dir: overrides
  language: es
  logo: assets/images/logo.png
  logo_width: 400
  favicon: assets/images/logo.ico
  icon:
    repo: fontawesome/brands/git-alt

  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link

  palette:
    primary: 'blue'
    accent: 'amber'

  font:
    text: 'Roboto'
    code: 'Fira Code'

  # GitHub
repo_url: https://github.com/ivangarciaalcaide/techdocs
repo_name: 'techdocs'

extra_css:
  - assets/stylesheets/footer.css
  - assets/stylesheets/extra.css

plugins:
  - search
  - include-markdown
  - exclude-search:
      exclude:
        - entendiendo_uefi/.includes/*
        - assets/**

markdown_extensions:
     - codehilite:
         guess_lang: false
     - pymdownx.highlight:
         anchor_linenums: true
         use_pygments: true
         linenums: true
     - pymdownx.superfences
     - attr_list
     - admonition
     - pymdownx.tasklist:
         custom_checkbox: true
         clickable_checkbox: true
     - pymdownx.tilde
     - toc:
         permalink: true
         toc_depth: 3

nav:
  - "": index.md
  - GNU/Linux:
      - Configuración Apache2 para Adminer: configuracion_apache_para_adminer.md
  - Manuales:
      - Entendiendo UEFI:
        - Introducción: entendiendo_uefi/01-introduccion.md
        - Conceptos básicos de almacenamiento: entendiendo_uefi/02-conceptos_basicos_almacenamiento.md
        - Glosario: entendiendo_uefi/99-glosario.md