site_name: Trucos y recordatorios de IT
site_description: Proyecto personal con trucos y recordatorios de IT
site_author: Tecnicaso
site_url: https://techdocs.ivangarciaalcaide.es

theme:
  name: material
  custom_dir: overrides
  language: es
  logo: assets/images/logo.png
  logo_width: 400
  favicon: assets/images/logo.ico
  icon:
    repo: fontawesome/brands/git-alt

  features:
    - content.code.annotate
    - content.code.copy

  palette:
    primary: 'blue'
    accent: 'amber'

  font:
    text: 'Roboto'
    code: 'Fira Code'

  # GitHub
repo_url: https://github.com/ivangarciaalcaide/techdocs
repo_name: 'techdocs'

extra_css:
  - assets/stylesheets/footer.css
  - assets/stylesheets/extra.css

markdown_extensions:
     - codehilite:
         guess_lang: false
     - pymdownx.highlight:
         anchor_linenums: true
         use_pygments: true
         linenums: true
     - pymdownx.superfences