site_name: Trucos y recordatorios de IT
site_description: Proyecto personal con trucos y recordatorios de IT
site_author: Tecnicaso
site_url: https://techdocs.ivangarciaalcaide.es

theme:
  name: material
  custom_dir: overrides/
  language: es
  logo: assets/images/logo.png
  logo_width: 400
  favicon: assets/images/logo.ico
  icon:
    repo: fontawesome/brands/git-alt

  features:
    - content.code.annotate
    - content.code.clipboard
    - content.code.copy
    - content.code.highlight
    - content.footnotes
    - content.icons
    - content.tables
    - content.tabs.link
    - navigation.instant
    - navigation.tabs

  palette:
    primary: 'blue'
    accent: 'amber'

  font:
    text: 'Roboto'
    code: 'Fira Code'

  # GitHub
repo_url: https://github.com/ivangarciaalcaide/techdocs
repo_name: 'techdocs'

extra_css:
  - assets/stylesheets/footer.css
  - assets/stylesheets/extra.css

plugins:
  - search
  - macros
  - include-markdown
  - exclude-search:
      exclude:
        - entendiendo_uefi/.includes/*
        - assets/**

markdown_extensions:
   - admonition
   - attr_list
   - codehilite:
       guess_lang: false
   - pymdownx.details
   - pymdownx.highlight:
       anchor_linenums: true
       use_pygments: true
       linenums: true
   - pymdownx.superfences:
       custom_fences:
         - name: mermaid
           class: mermaid
           format: !!python/name:pymdownx.superfences.fence_code_format
   - pymdownx.tasklist:
       custom_checkbox: true
       clickable_checkbox: true
   - pymdownx.tilde
   - toc:
       permalink: true
       toc_depth: 3

nav:
  - "": index.md
  - GNU/Linux:
      - Configuración Apache2 para Adminer: configuracion_apache_para_adminer.md
  - Manuales:
      - Entendiendo UEFI:
        - Índice: entendiendo_uefi/index_uefi.md
        - Introducción: entendiendo_uefi/01-introduccion.md
        - Conceptos básicos: entendiendo_uefi/02-conceptos_basicos.md
        - Gestión del registro de arranque UEFI (NVRAM): entendiendo_uefi/03-gestion_nvram.md
        - Glosario: entendiendo_uefi/99-glosario.md